### ISSUE TITLE
Unable to build on macOS 10.12.4

### ISSUE THREAD

**Issue by RUSshy** [SwiftGFX/SwiftBGFX#4]
Hello, 

I added the lib in the Package.swift file

```
dependencies: [
                .Package(url: "https://github.com/SwiftGFX/SwiftBGFX.git", majorVersion: 1, minor: 0),
        ]
``` 

Then it gave me an error: 

```make
RUSshys-iMac:Test RUSshy$ swift build
Fetching https://github.com/SwiftGFX/SwiftBGFX.git
Fetching https://github.com/SwiftGFX/SwiftMath
Cloning https://github.com/SwiftGFX/SwiftBGFX.git
Resolving https://github.com/SwiftGFX/SwiftBGFX.git at 1.0.0
Cloning https://github.com/SwiftGFX/SwiftMath
Resolving https://github.com/SwiftGFX/SwiftMath at 2.2.2
Compile Swift Module 'SwiftMath' (25 sources)
Compile Cbgfx dummy.cpp
Archiving /Users/RUSshy/Projects/Swift/Test/.build/debug/libSwiftMath.a
Linking Cbgfx
Undefined symbols for architecture x86_64:
  "_bgfx_init", referenced from:
      dummy() in dummy.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
```

**Comment by s1ddok** [comment]
Well, that's because the process is kinda complicated and doesn't work straight away. Check how it is done here: https://github.com/s1ddok/Fiber2D

To be short: this is due to limitations that SwiftPM has. We will fix it as soon as SwiftPM will support local config/prebuilt C++/C libs.
